### NUMPY Numerical Python
#### Numpy Arrays
They come in two flavours:
- Vectors - They are 1-Dimensional (1-d)
- Matrices - They are 2-Dimensional (2-d)

In [2]:
import numpy as np

In [4]:
# How to create a numpy array
num = list(range(10))
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
num_array = np.array(num)
num_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(num_array)

numpy.ndarray

In [11]:
# How to create a metrix using a list
num1 = list(range(1,4))
num2 = list(range(5,8))
num3 = list(range(7,10))

print(f"{num1}, {num2}, {num3}")

[1, 2, 3], [5, 6, 7], [7, 8, 9]


In [13]:
matrix = np.array([num1, num2, num3])
matrix

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [14]:
matrix.shape

(3, 3)

#### Built in methods in Numpy
- arange
- reshape
- zeros
- ones
- linspace
- eyes

In [30]:
# Arange
range(1,10)

range(1, 10)

In [16]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
test = np.arange(1, 11)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
test.shape

(10,)

In [31]:
# Reshape
test_new = test.reshape(5,2)
test_new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
test2 = np.arange(1,26)
test2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [29]:
test2.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
# Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
# 2D
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
# Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Linspace -  Gives evenly spaced numbers
lin = np.linspace(1,10)
lin

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [41]:
lin.shape

(50,)

In [42]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [43]:
# Eyes - Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Indexing and SLicing