### NUMPY Numerical Python
#### Numpy Arrays
They come in two flavours:
- Vectors - They are 1-Dimensional (1-d)
- Matrices - They are 2-Dimensional (2-d)

In [1]:
import numpy as np

In [2]:
# How to create a numpy array
num = list(range(10))
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
num_array = np.array(num)
num_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(num_array)

numpy.ndarray

In [5]:
# How to create a metrix using a list
num1 = list(range(1,4))
num2 = list(range(5,8))
num3 = list(range(7,10))

print(f"{num1}, {num2}, {num3}")

[1, 2, 3], [5, 6, 7], [7, 8, 9]


In [6]:
matrix = np.array([num1, num2, num3])
matrix

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [7]:
matrix.shape

(3, 3)

#### Built in methods in Numpy
- arange
- reshape
- zeros
- ones
- linspace
- eyes

In [8]:
# Arange
range(1,10)

range(1, 10)

In [9]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
test = np.arange(1, 11)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
test.shape

(10,)

In [12]:
# Reshape
test_new = test.reshape(5,2)
test_new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
test2 = np.arange(1,26)
test2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [14]:
test2.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# 2D
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# Linspace -  Gives evenly spaced numbers
lin = np.linspace(1,10)
lin

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
lin.shape

(50,)

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
# Eyes - Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Indexing and SLicing

In [24]:
test = np.arange(1,37)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [25]:
# Indexing - returns one value
test[-2] # Negative indexing

35

In [26]:
test[35] # Positive indexing

36

In [27]:
# SLicing - returns multiple values
test[0:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Move by two step
test[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36])

In [29]:
# Odd numbers
test[0::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [30]:
# Jumping 5 times
test[4::5]

array([ 5, 10, 15, 20, 25, 30, 35])

In [31]:
test.shape

(36,)

In [32]:
test2 = test.reshape(6,6)
test2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [33]:
test2.shape

(6, 6)

In [34]:
# Indexing and Slicing
test2[5]

array([31, 32, 33, 34, 35, 36])

In [35]:
test2[5][3:]

array([34, 35, 36])

In [36]:
test2[3][1:4]

array([20, 21, 22])

In [37]:
test2[5][:3]

array([31, 32, 33])

In [38]:
# [Row, Column]
test2[1:4, 3:]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])

In [39]:
test2[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

### Random - Rand, Randn, and Randint

In [40]:
# Rand - Random numbers from a uniform distribution (0 & 1)
test = np.random.rand(5)
test

array([0.73234007, 0.27593074, 0.42834969, 0.41567641, 0.81764806])

In [41]:
test.shape

(5,)

In [42]:
test2 = np.random.rand(6,5)
test2

array([[0.23501979, 0.60846003, 0.19858839, 0.93395738, 0.66169578],
       [0.23877002, 0.22275638, 0.59667923, 0.02436908, 0.1990652 ],
       [0.87608196, 0.56333761, 0.90787964, 0.55069716, 0.96771255],
       [0.02359388, 0.65006304, 0.41744035, 0.58194751, 0.51768308],
       [0.17266763, 0.24363888, 0.53852194, 0.34632305, 0.4730609 ],
       [0.59844982, 0.31999131, 0.56068621, 0.07107029, 0.75396985]])

In [43]:
# Randn - Random numbers from a normal distribution (Mean=Median=Mode i.e. Mean = 0 and variance = 1)
num = np.random.randn(5)
num

array([ 0.84770407,  0.28079546, -0.25191819, -0.92699064,  0.50867337])

In [44]:
num2 = np.random.randn(5,5)
num2

array([[ 1.74954568,  2.22078141, -1.75450698,  0.56299621,  1.66844571],
       [ 0.81821249,  0.2440115 , -1.55820078, -1.69283861,  0.69539812],
       [-1.23912492,  0.40950326, -1.21124979, -0.89481558,  0.80553314],
       [-1.22951331, -0.47288367,  0.16406667,  0.26842361,  0.69147078],
       [-0.05724007, -0.01349056,  1.40573984, -0.72030576, -1.4276411 ]])

In [45]:
# Randint - Random integers (Start from low to high value)
test = np.random.randint(10, 100, 5)
test

array([86, 80, 97, 41, 35])

In [46]:
# MAx, Min, Argmax, Argmin
test2

array([[0.23501979, 0.60846003, 0.19858839, 0.93395738, 0.66169578],
       [0.23877002, 0.22275638, 0.59667923, 0.02436908, 0.1990652 ],
       [0.87608196, 0.56333761, 0.90787964, 0.55069716, 0.96771255],
       [0.02359388, 0.65006304, 0.41744035, 0.58194751, 0.51768308],
       [0.17266763, 0.24363888, 0.53852194, 0.34632305, 0.4730609 ],
       [0.59844982, 0.31999131, 0.56068621, 0.07107029, 0.75396985]])

In [47]:
# Max - Maximum value in Array
test2.max()

0.9677125505717378

In [48]:
# Min - Minimum value in Array
test2.min()

0.0235938781242786

In [49]:
# Argmax - The index of the maximum value
test2.argmax()

14

In [50]:
# Argmin - The index of the minimum value
test2.argmin()

15